version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: iggydev-wordpress-staging2_wordpress_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  wordpress:
    image: wordpress:7.1.2
    user: "1000:1000"
    environment:
      WORDPRESS_DB_HOST: iggydev-wordpress-staging2_db_1
      WORDPRESS_DB_NAME: iggyshikes
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress-staging2
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    restart: on-failure
    depends_on:
      - db

  db:
    image: mariadb:11.8
    user: "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-staging2-root
      MYSQL_DATABASE: iggyshikes
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress-staging2
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    restart: on-failure
